//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eaton_DG_PCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alarm_Info_History
    {
        public int ID { get; set; }
        public string DeviceId { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public string Value { get; set; }
        public Nullable<int> AlarmNum { get; set; }
        public string IsShow { get; set; }
        public string IsResumed { get; set; }
        public Nullable<System.DateTime> ResumeTime { get; set; }
        public string Remark { get; set; }
        public string Variable_Address { get; set; }
    }
}
