//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eaton_DG_PCC.Models
{
    using System;
    using System.Collections.Generic;

    public partial class AllStatus
    {
        public int ID { get; set; }
        public string LineID { get; set; }
        public string RecordTime { get; set; }
        //public Nullable<System.DateTime> Ts { get; set; }
        public string ProductID { get; set; }
        public string DutMode { get; set; }
        public int DutTotalNum { get; set; }
        public int DutPassNum { get; set; }
        public int DutFailNum { get; set; }
        //public Nullable<System.DateTime> Ts { get; set; }
        public double DutFailRate { get; set; }
        //public Nullable<System.DateTime> SaveTs { get; set; }
        public int cap { get; set; }


        public int ESR { get; set; }
        //public Nullable<System.DateTime> Ts { get; set; }
        public int Voltage { get; set; }
        //public Nullable<System.DateTime> SaveTs { get; set; }
        public int HaltNum { get; set; }
        public int HaltTime { get; set; }
        //public Nullable<System.DateTime> Ts { get; set; }
        public int DevStatus { get; set; }
        //public Nullable<System.DateTime> SaveTs { get; set; }
        public string DeviceUseRate { get; set; }

    }
}
