//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eaton_DG_PCC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DRAQ127Entities : DbContext
    {
        public DRAQ127Entities()
            : base("name=DRAQ127Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alarm_Info_History> Alarm_Info_History { get; set; }
        public virtual DbSet<Daily_Output_Model> Daily_Output_Model { get; set; }
        public virtual DbSet<DRAQ127> DRAQ127 { get; set; }
        public virtual DbSet<Fault_Point_Distribution> Fault_Point_Distribution { get; set; }
        public virtual DbSet<Hourly_Output_Model> Hourly_Output_Model { get; set; }
        public virtual DbSet<Monthly_Order_Info> Monthly_Order_Info { get; set; }
        public virtual DbSet<Monthly_Output_Model> Monthly_Output_Model { get; set; }
        public virtual DbSet<Record_of_Spare_Parts> Record_of_Spare_Parts { get; set; }
        public virtual DbSet<Alarm_real_time> Alarm_real_time { get; set; }
    }
}
