//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eaton_DG_PCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fault_Point_Distribution
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Ts { get; set; }
        public Nullable<int> Years { get; set; }
        public Nullable<int> Months { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<int> Ready_Load { get; set; }
        public Nullable<int> Loading { get; set; }
        public Nullable<int> Test_Station1 { get; set; }
        public Nullable<int> Test_Station2 { get; set; }
        public Nullable<int> Test_Station3 { get; set; }
        public Nullable<int> Test_Station4 { get; set; }
        public Nullable<int> Rotation_Table { get; set; }
        public Nullable<int> CCD_Scan { get; set; }
        public Nullable<int> Unloading { get; set; }
        public Nullable<int> Pack { get; set; }
    }
}
