//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eaton_DG_PCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hourly_Output_Model
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Ts { get; set; }
        public Nullable<int> Years { get; set; }
        public Nullable<int> Months { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<int> Q127_100_Output { get; set; }
        public Nullable<int> Q127_150_Output { get; set; }
        public Nullable<int> Q127_220_Output { get; set; }
        public Nullable<int> Q127_330_Output { get; set; }
        public Nullable<int> Q127_470_Output { get; set; }
        public Nullable<int> A127_R47_Output { get; set; }
        public Nullable<int> A127_1R0_Output { get; set; }
        public Nullable<int> A127_1R5_Output { get; set; }
        public Nullable<int> A127_2R2_Output { get; set; }
        public Nullable<int> A127_3R3_Output { get; set; }
        public Nullable<int> A127_4R7_Output { get; set; }
        public Nullable<int> A127_6R8_Output { get; set; }
        public Nullable<int> A127_8R2_Output { get; set; }
        public Nullable<int> A127_100_Output { get; set; }
        public Nullable<int> A127_150_Output { get; set; }
        public Nullable<int> A127_220_Output { get; set; }
        public Nullable<int> A127_330_Output { get; set; }
        public Nullable<int> A127_470_Output { get; set; }
        public Nullable<int> A127_680_Output { get; set; }
        public Nullable<int> A127_820_Output { get; set; }
        public Nullable<int> A127_101_Output { get; set; }
        public Nullable<int> A127_151_Output { get; set; }
        public Nullable<int> A127_221_Output { get; set; }
        public Nullable<int> A127_331_Output { get; set; }
        public Nullable<int> A127_471_Output { get; set; }
        public Nullable<int> A127_681_Output { get; set; }
        public Nullable<int> A127_821_Output { get; set; }
        public Nullable<int> A127_102_Output { get; set; }
        public Nullable<int> A125_R47_Output { get; set; }
        public Nullable<int> A125_1R0_Output { get; set; }
        public Nullable<int> A125_1R5_Output { get; set; }
        public Nullable<int> A125_2R2_Output { get; set; }
        public Nullable<int> A125_3R3_Output { get; set; }
        public Nullable<int> A125_4R7_Output { get; set; }
        public Nullable<int> A125_6R8_Output { get; set; }
        public Nullable<int> A125_8R2_Output { get; set; }
        public Nullable<int> A125_100_Output { get; set; }
        public Nullable<int> A125_150_Output { get; set; }
        public Nullable<int> A125_220_Output { get; set; }
        public Nullable<int> A125_330_Output { get; set; }
        public Nullable<int> A125_470_Output { get; set; }
        public Nullable<int> A125_680_Output { get; set; }
        public Nullable<int> A125_820_Output { get; set; }
        public Nullable<int> A125_101_Output { get; set; }
        public Nullable<int> A125_151_Output { get; set; }
        public Nullable<int> A125_221_Output { get; set; }
        public Nullable<int> A125_331_Output { get; set; }
        public Nullable<int> A125_471_Output { get; set; }
        public Nullable<int> A125_681_Output { get; set; }
        public Nullable<int> A125_821_Output { get; set; }
        public Nullable<int> A125_102_Output { get; set; }
        public Nullable<int> A124_R47_Output { get; set; }
        public Nullable<int> A124_1R0_Output { get; set; }
        public Nullable<int> A124_1R5_Output { get; set; }
        public Nullable<int> A124_2R2_Output { get; set; }
        public Nullable<int> A124_3R3_Output { get; set; }
        public Nullable<int> A124_4R7_Output { get; set; }
        public Nullable<int> A124_6R8_Output { get; set; }
        public Nullable<int> A124_8R2_Output { get; set; }
        public Nullable<int> A124_100_Output { get; set; }
        public Nullable<int> A124_150_Output { get; set; }
        public Nullable<int> A124_220_Output { get; set; }
        public Nullable<int> A124_330_Output { get; set; }
        public Nullable<int> A124_470_Output { get; set; }
        public Nullable<int> A124_680_Output { get; set; }
        public Nullable<int> A124_820_Output { get; set; }
        public Nullable<int> A124_101_Output { get; set; }
        public Nullable<int> A124_151_Output { get; set; }
        public Nullable<int> A124_221_Output { get; set; }
        public Nullable<int> A124_331_Output { get; set; }
        public Nullable<int> A124_471_Output { get; set; }
        public Nullable<int> A124_681_Output { get; set; }
        public Nullable<int> A124_821_Output { get; set; }
        public Nullable<int> A124_102_Output { get; set; }
        public Nullable<int> Q127_100_NG { get; set; }
        public Nullable<int> Q127_150_NG { get; set; }
        public Nullable<int> Q127_220_NG { get; set; }
        public Nullable<int> Q127_330_NG { get; set; }
        public Nullable<int> Q127_470_NG { get; set; }
        public Nullable<int> A127_R47_NG { get; set; }
        public Nullable<int> A127_1R0_NG { get; set; }
        public Nullable<int> A127_1R5_NG { get; set; }
        public Nullable<int> A127_2R2_NG { get; set; }
        public Nullable<int> A127_3R3_NG { get; set; }
        public Nullable<int> A127_4R7_NG { get; set; }
        public Nullable<int> A127_6R8_NG { get; set; }
        public Nullable<int> A127_8R2_NG { get; set; }
        public Nullable<int> A127_100_NG { get; set; }
        public Nullable<int> A127_150_NG { get; set; }
        public Nullable<int> A127_220_NG { get; set; }
        public Nullable<int> A127_330_NG { get; set; }
        public Nullable<int> A127_470_NG { get; set; }
        public Nullable<int> A127_680_NG { get; set; }
        public Nullable<int> A127_820_NG { get; set; }
        public Nullable<int> A127_101_NG { get; set; }
        public Nullable<int> A127_151_NG { get; set; }
        public Nullable<int> A127_221_NG { get; set; }
        public Nullable<int> A127_331_NG { get; set; }
        public Nullable<int> A127_471_NG { get; set; }
        public Nullable<int> A127_681_NG { get; set; }
        public Nullable<int> A127_821_NG { get; set; }
        public Nullable<int> A127_102_NG { get; set; }
        public Nullable<int> A125_R47_NG { get; set; }
        public Nullable<int> A125_1R0_NG { get; set; }
        public Nullable<int> A125_1R5_NG { get; set; }
        public Nullable<int> A125_2R2_NG { get; set; }
        public Nullable<int> A125_3R3_NG { get; set; }
        public Nullable<int> A125_4R7_NG { get; set; }
        public Nullable<int> A125_6R8_NG { get; set; }
        public Nullable<int> A125_8R2_NG { get; set; }
        public Nullable<int> A125_100_NG { get; set; }
        public Nullable<int> A125_150_NG { get; set; }
        public Nullable<int> A125_220_NG { get; set; }
        public Nullable<int> A125_330_NG { get; set; }
        public Nullable<int> A125_470_NG { get; set; }
        public Nullable<int> A125_680_NG { get; set; }
        public Nullable<int> A125_820_NG { get; set; }
        public Nullable<int> A125_101_NG { get; set; }
        public Nullable<int> A125_151_NG { get; set; }
        public Nullable<int> A125_221_NG { get; set; }
        public Nullable<int> A125_331_NG { get; set; }
        public Nullable<int> A125_471_NG { get; set; }
        public Nullable<int> A125_681_NG { get; set; }
        public Nullable<int> A125_821_NG { get; set; }
        public Nullable<int> A125_102_NG { get; set; }
        public Nullable<int> A124_R47_NG { get; set; }
        public Nullable<int> A124_1R0_NG { get; set; }
        public Nullable<int> A124_1R5_NG { get; set; }
        public Nullable<int> A124_2R2_NG { get; set; }
        public Nullable<int> A124_3R3_NG { get; set; }
        public Nullable<int> A124_4R7_NG { get; set; }
        public Nullable<int> A124_6R8_NG { get; set; }
        public Nullable<int> A124_8R2_NG { get; set; }
        public Nullable<int> A124_100_NG { get; set; }
        public Nullable<int> A124_150_NG { get; set; }
        public Nullable<int> A124_220_NG { get; set; }
        public Nullable<int> A124_330_NG { get; set; }
        public Nullable<int> A124_470_NG { get; set; }
        public Nullable<int> A124_680_NG { get; set; }
        public Nullable<int> A124_820_NG { get; set; }
        public Nullable<int> A124_101_NG { get; set; }
        public Nullable<int> A124_151_NG { get; set; }
        public Nullable<int> A124_221_NG { get; set; }
        public Nullable<int> A124_331_NG { get; set; }
        public Nullable<int> A124_471_NG { get; set; }
        public Nullable<int> A124_681_NG { get; set; }
        public Nullable<int> A124_821_NG { get; set; }
        public Nullable<int> A124_102_NG { get; set; }
    }
}
