//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eaton_DG_PCC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SYRSCMEntities : DbContext
    {
        public SYRSCMEntities()
            : base("name=SYRSCMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<saiyuan> saiyuan { get; set; }
        public virtual DbSet<saiyuan1> saiyuan1 { get; set; }
        public virtual DbSet<saiyuan10> saiyuan10 { get; set; }
        public virtual DbSet<saiyuan2> saiyuan2 { get; set; }
        public virtual DbSet<saiyuan3> saiyuan3 { get; set; }
        public virtual DbSet<saiyuan4> saiyuan4 { get; set; }
        public virtual DbSet<saiyuan5> saiyuan5 { get; set; }
        public virtual DbSet<saiyuan6> saiyuan6 { get; set; }
        public virtual DbSet<saiyuan7> saiyuan7 { get; set; }
        public virtual DbSet<saiyuan8> saiyuan8 { get; set; }
        public virtual DbSet<saiyuan9> saiyuan9 { get; set; }
        public virtual DbSet<saiyuan99> saiyuan99 { get; set; }
        public virtual DbSet<Test> Test { get; set; }
    }
}
