//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eaton_DG_PCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monthly_Order_Info
    {
        public int ID { get; set; }
        public string DeviceId { get; set; }
        public Nullable<System.DateTime> Ts { get; set; }
        public Nullable<int> Years { get; set; }
        public Nullable<int> Months { get; set; }
        public string Orders { get; set; }
        public string Model { get; set; }
        public Nullable<int> Plan_Output { get; set; }
        public Nullable<int> Output { get; set; }
        public Nullable<int> NG { get; set; }
        public string Done_Ratio { get; set; }
        public Nullable<int> User_Hours { get; set; }
        public Nullable<int> Mark { get; set; }
        public Nullable<int> Impulse { get; set; }
        public Nullable<int> Hi_Put { get; set; }
        public Nullable<int> Comprehensive { get; set; }
        public Nullable<int> DCR { get; set; }
        public Nullable<int> CCD { get; set; }
        public Nullable<int> Days { get; set; }
    }
}
