//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eaton_DG_PCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record_of_Spare_Parts
    {
        public int id { get; set; }
        public string Replace_Date { get; set; }
        public string Replace_content { get; set; }
        public string Operator { get; set; }
        public string Telephone { get; set; }
    }
}
