//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eaton_DG_PCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int ID { get; set; }
        public string DeviceId { get; set; }
        public string Ts { get; set; }
        public string Test1 { get; set; }
        public string Test2 { get; set; }
        public string Test3 { get; set; }
        public string Test4 { get; set; }
        public string Test5 { get; set; }
        public string Test6 { get; set; }
        public string Test7 { get; set; }
        public string Test8 { get; set; }
        public string Test9 { get; set; }
        public string Test10 { get; set; }
        public string Test11 { get; set; }
        public string Test12 { get; set; }
        public string Test13 { get; set; }
        public string Test14 { get; set; }
        public string Test15 { get; set; }
        public string Test16 { get; set; }
        public string Test17 { get; set; }
        public string Test18 { get; set; }
        public string Test19 { get; set; }
        public string Test20 { get; set; }
        public string Test21 { get; set; }
        public string Test22 { get; set; }
        public string Test23 { get; set; }
        public string Test24 { get; set; }
        public string Test25 { get; set; }
        public string Test26 { get; set; }
        public string Test27 { get; set; }
        public string Test28 { get; set; }
        public string Test29 { get; set; }
        public string Test30 { get; set; }
        public string Test31 { get; set; }
        public string Test32 { get; set; }
        public string Test33 { get; set; }
        public string Test34 { get; set; }
        public string Test35 { get; set; }
        public string Test36 { get; set; }
        public string Test37 { get; set; }
        public string Test38 { get; set; }
        public string Test39 { get; set; }
        public string Test40 { get; set; }
        public string Test41 { get; set; }
        public string Test42 { get; set; }
        public string Test43 { get; set; }
        public string Test44 { get; set; }
        public string Test45 { get; set; }
        public string Test46 { get; set; }
        public string Test47 { get; set; }
        public string Test48 { get; set; }
        public string Test49 { get; set; }
        public string Test50 { get; set; }
        public string Test51 { get; set; }
        public string Test52 { get; set; }
        public string Test53 { get; set; }
        public string Test54 { get; set; }
        public string Test55 { get; set; }
        public string Test56 { get; set; }
        public string Test57 { get; set; }
        public string Test58 { get; set; }
        public string Test59 { get; set; }
        public string Test60 { get; set; }
        public string Test61 { get; set; }
        public string Test62 { get; set; }
        public string Test63 { get; set; }
        public string Test64 { get; set; }
        public string Test65 { get; set; }
        public string Test66 { get; set; }
        public string Test67 { get; set; }
        public string Test68 { get; set; }
        public string Test69 { get; set; }
        public string Test70 { get; set; }
        public string Test71 { get; set; }
        public string Test72 { get; set; }
        public string Test73 { get; set; }
        public string Test74 { get; set; }
        public string Test75 { get; set; }
        public string Test76 { get; set; }
        public string Test77 { get; set; }
        public string Test78 { get; set; }
        public string Test79 { get; set; }
        public string Test80 { get; set; }
        public string Test81 { get; set; }
        public string Test82 { get; set; }
        public string Test83 { get; set; }
        public string Test84 { get; set; }
        public string Test85 { get; set; }
        public string Test86 { get; set; }
        public string Test87 { get; set; }
        public string Test88 { get; set; }
        public string Test89 { get; set; }
        public string Test90 { get; set; }
        public string Test91 { get; set; }
        public string Test92 { get; set; }
        public string Test93 { get; set; }
        public string Test94 { get; set; }
        public string Test95 { get; set; }
        public string Test96 { get; set; }
        public string Test97 { get; set; }
        public string Test98 { get; set; }
        public string Test99 { get; set; }
        public string Test100 { get; set; }
    }
}
