using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Eaton_DG_PCC.Model
{
    public class Monthly_Output_Model
    {
        public int ID { get; set; }
        public string Ts { get; set; }
        public string Years { get; set; }
        public string Months { get; set; }
        public string Model_Output_1 { get; set; }
        public string Model_Output_2 { get; set; }
        public string Model_Output_3 { get; set; }
        public string Model_Output_4 { get; set; }
        public string Model_Output_5 { get; set; }
        public string Model_Output_6 { get; set; }
        public string Model_Output_7 { get; set; }
        public string Model_Output_8 { get; set; }
        public string Model_Output_9 { get; set; }
        public string Model_Output_10 { get; set; }
        public string Model_Output_11 { get; set; }
        public string Model_Output_12 { get; set; }
        public string Model_Output_13 { get; set; }
        public string Model_Output_14 { get; set; }
        public string Model_Output_15 { get; set; }
        public string Model_Output_16 { get; set; }
        public string Model_Output_17 { get; set; }
        public string Model_Output_18 { get; set; }
        public string Model_Output_19 { get; set; }
        public string Model_Output_20 { get; set; }
        public string Model_Output_21 { get; set; }
        public string Model_Output_22 { get; set; }
        public string Model_Output_23 { get; set; }
        public string Model_Output_24 { get; set; }
        public string Model_Output_25 { get; set; }
        public string Model_Output_26 { get; set; }
        public string Model_Output_27 { get; set; }
        public string Model_Output_28 { get; set; }
        public string Model_Output_29 { get; set; }
        public string Model_Output_30 { get; set; }
        public string Model_Output_31 { get; set; }
        public string Model_Output_32 { get; set; }
        public string Model_Output_33 { get; set; }
        public string Model_Output_34 { get; set; }
        public string Model_Output_35 { get; set; }
        public string Model_Output_36 { get; set; }
        public string Model_Output_37 { get; set; }
        public string Model_Output_38 { get; set; }
        public string Model_Output_39 { get; set; }
        public string Model_Output_40 { get; set; }
        public string Model_Output_41 { get; set; }
        public string Model_Output_42 { get; set; }
        public string Model_Output_43 { get; set; }
        public string Model_Output_44 { get; set; }
        public string Model_Output_45 { get; set; }
        public string Model_Output_46 { get; set; }
        public string Model_Output_47 { get; set; }
        public string Model_Output_48 { get; set; }
        public string Model_Output_49 { get; set; }
        public string Model_Output_50 { get; set; }
        public string Model_Output_51 { get; set; }
        public string Model_Output_52 { get; set; }
        public string Model_Output_53 { get; set; }
        public string Model_Output_54 { get; set; }
        public string Model_Output_55 { get; set; }
        public string Model_Output_56 { get; set; }
        public string Model_Output_57 { get; set; }
        public string Model_Output_58 { get; set; }
        public string Model_Output_59 { get; set; }
        public string Model_Output_60 { get; set; }
        public string Model_Output_61 { get; set; }
        public string Model_Output_62 { get; set; }
        public string Model_Output_63 { get; set; }
        public string Model_Output_64 { get; set; }
        public string Model_Output_65 { get; set; }
        public string Model_Output_66 { get; set; }
        public string Model_Output_67 { get; set; }
        public string Model_Output_68 { get; set; }
        public string Model_Output_69 { get; set; }
        public string Model_Output_70 { get; set; }
        public string Model_Output_71 { get; set; }
        public string Model_Output_72 { get; set; }
        public string Model_Output_73 { get; set; }
        public string Model_Output_74 { get; set; }
        public string Model_Output_75 { get; set; }
        public string Model_Output_76 { get; set; }
        public string Model_Output_77 { get; set; }
        public string Model_Output_78 { get; set; }
        public string Model_Output_79 { get; set; }
        public string Model_Output_80 { get; set; }
        public string Model_Output_81 { get; set; }
        public string Model_Output_82 { get; set; }
        public string Model_Output_83 { get; set; }
        public string Model_Output_84 { get; set; }
        public string Model_Output_85 { get; set; }
        public string Model_Output_86 { get; set; }
        public string Model_Output_87 { get; set; }
        public string Model_Output_88 { get; set; }
        public string Model_Output_89 { get; set; }
        public string Model_Output_90 { get; set; }
        public string Model_Output_91 { get; set; }
        public string Model_Output_92 { get; set; }
        public string Model_Output_93 { get; set; }
        public string Model_Output_94 { get; set; }
        public string Model_Output_95 { get; set; }
        public string Model_Output_96 { get; set; }
        public string Model_Output_97 { get; set; }
        public string Model_Output_98 { get; set; }
        public string Model_Output_99 { get; set; }
        public string Model_Output_100 { get; set; }
        public string Model_NG_1 { get; set; }
        public string Model_NG_2 { get; set; }
        public string Model_NG_3 { get; set; }
        public string Model_NG_4 { get; set; }
        public string Model_NG_5 { get; set; }
        public string Model_NG_6 { get; set; }
        public string Model_NG_7 { get; set; }
        public string Model_NG_8 { get; set; }
        public string Model_NG_9 { get; set; }
        public string Model_NG_10 { get; set; }
        public string Model_NG_11 { get; set; }
        public string Model_NG_12 { get; set; }
        public string Model_NG_13 { get; set; }
        public string Model_NG_14 { get; set; }
        public string Model_NG_15 { get; set; }
        public string Model_NG_16 { get; set; }
        public string Model_NG_17 { get; set; }
        public string Model_NG_18 { get; set; }
        public string Model_NG_19 { get; set; }
        public string Model_NG_20 { get; set; }
        public string Model_NG_21 { get; set; }
        public string Model_NG_22 { get; set; }
        public string Model_NG_23 { get; set; }
        public string Model_NG_24 { get; set; }
        public string Model_NG_25 { get; set; }
        public string Model_NG_26 { get; set; }
        public string Model_NG_27 { get; set; }
        public string Model_NG_28 { get; set; }
        public string Model_NG_29 { get; set; }
        public string Model_NG_30 { get; set; }
        public string Model_NG_31 { get; set; }
        public string Model_NG_32 { get; set; }
        public string Model_NG_33 { get; set; }
        public string Model_NG_34 { get; set; }
        public string Model_NG_35 { get; set; }
        public string Model_NG_36 { get; set; }
        public string Model_NG_37 { get; set; }
        public string Model_NG_38 { get; set; }
        public string Model_NG_39 { get; set; }
        public string Model_NG_40 { get; set; }
        public string Model_NG_41 { get; set; }
        public string Model_NG_42 { get; set; }
        public string Model_NG_43 { get; set; }
        public string Model_NG_44 { get; set; }
        public string Model_NG_45 { get; set; }
        public string Model_NG_46 { get; set; }
        public string Model_NG_47 { get; set; }
        public string Model_NG_48 { get; set; }
        public string Model_NG_49 { get; set; }
        public string Model_NG_50 { get; set; }
        public string Model_NG_51 { get; set; }
        public string Model_NG_52 { get; set; }
        public string Model_NG_53 { get; set; }
        public string Model_NG_54 { get; set; }
        public string Model_NG_55 { get; set; }
        public string Model_NG_56 { get; set; }
        public string Model_NG_57 { get; set; }
        public string Model_NG_58 { get; set; }
        public string Model_NG_59 { get; set; }
        public string Model_NG_60 { get; set; }
        public string Model_NG_61 { get; set; }
        public string Model_NG_62 { get; set; }
        public string Model_NG_63 { get; set; }
        public string Model_NG_64 { get; set; }
        public string Model_NG_65 { get; set; }
        public string Model_NG_66 { get; set; }
        public string Model_NG_67 { get; set; }
        public string Model_NG_68 { get; set; }
        public string Model_NG_69 { get; set; }
        public string Model_NG_70 { get; set; }
        public string Model_NG_71 { get; set; }
        public string Model_NG_72 { get; set; }
        public string Model_NG_73 { get; set; }
        public string Model_NG_74 { get; set; }
        public string Model_NG_75 { get; set; }
        public string Model_NG_76 { get; set; }
        public string Model_NG_77 { get; set; }
        public string Model_NG_78 { get; set; }
        public string Model_NG_79 { get; set; }
        public string Model_NG_80 { get; set; }
        public string Model_NG_81 { get; set; }
        public string Model_NG_82 { get; set; }
        public string Model_NG_83 { get; set; }
        public string Model_NG_84 { get; set; }
        public string Model_NG_85 { get; set; }
        public string Model_NG_86 { get; set; }
        public string Model_NG_87 { get; set; }
        public string Model_NG_88 { get; set; }
        public string Model_NG_89 { get; set; }
        public string Model_NG_90 { get; set; }
        public string Model_NG_91 { get; set; }
        public string Model_NG_92 { get; set; }
        public string Model_NG_93 { get; set; }
        public string Model_NG_94 { get; set; }
        public string Model_NG_95 { get; set; }
        public string Model_NG_96 { get; set; }
        public string Model_NG_97 { get; set; }
        public string Model_NG_98 { get; set; }
        public string Model_NG_99 { get; set; }
        public string Model_NG_100 { get; set; }
    }
}